name: CloudSync Build and Test

on:
  push:
    branches: [ "master" ] # Adjust branch name if needed
  pull_request:
    branches: [ "master" ] # Adjust branch name if needed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' # Adjust Go version if needed

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
